In [1]:
import numpy as np

colors = ["r", "g", "b", "y", "w", "o"]
color_list = []
for _ in range(9):
    for i in colors:
        color_list.append(i)

a = np.matrix([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

color_list



['r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o',
 'r',
 'g',
 'b',
 'y',
 'w',
 'o']

In [2]:
len(color_list)

54

In [3]:
li = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
li = li.reshape(3, 3)

li.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [4]:
front = np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3)
front

array([['r', 'r', 'r'],
       ['r', 'r', 'r'],
       ['r', 'r', 'r']], dtype='<U1')

In [5]:
cube_dict = {

    "front": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "back": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "top": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "right": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "left": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "bottom": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3)

}

len(cube_dict)

6

In [6]:
for i in cube_dict:
    print(len(cube_dict[i]))

3
3
3
3
3
3


In [7]:
for i in cube_dict:

    for x in cube_dict[i]:
        print(x)

['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']
['r' 'r' 'r']


In [8]:
def test (a: tuple, b: int):

    print(a)
    print(b)


test(1, a=(1, 2))

TypeError: test() got multiple values for argument 'a'

In [ ]:
import numpy as np

cube_dict = {

    "front": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "back": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "top": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "right": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "left": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3),
    "bottom": np.array(["r", "r", "r", "r", "r", "r", "r", "r", "r"]).reshape(3, 3)

}

for i in cube_dict.values():

    print(i)

[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]
[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]
[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]
[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]
[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]
[['r' 'r' 'r']
 ['r' 'r' 'r']
 ['r' 'r' 'r']]


In [ ]:
import random

color_dict = {

    "r": 1,
    "g": 2,
    "b": 3,
    "y": 4,
    "o": 5,
    "w": 6
}

cube_list = []

for i in color_dict:

    for _ in range(9):

        cube_list.append(i)

np.random.shuffle(cube_list)


cube_list

['b',
 'y',
 'r',
 'o',
 'y',
 'w',
 'w',
 'g',
 'g',
 'r',
 'g',
 'y',
 'r',
 'w',
 'o',
 'g',
 'o',
 'w',
 'o',
 'r',
 'r',
 'y',
 'w',
 'b',
 'o',
 'g',
 'y',
 'o',
 'r',
 'w',
 'o',
 'y',
 'y',
 'g',
 'r',
 'w',
 'y',
 'r',
 'b',
 'g',
 'b',
 'w',
 'g',
 'b',
 'b',
 'b',
 'o',
 'w',
 'o',
 'b',
 'r',
 'y',
 'g',
 'b']

In [ ]:
side_list = ["front", "back", "top", "right", "left", "bottom"]
cube_dict = {}
num_cubes = int(len(cube_list) / len(side_list))

for x, i in enumerate(side_list):

    cube_dict[i] = np.array(cube_list[(x * num_cubes):(num_cubes * (x + 1))]).reshape(3, 3)
    



In [ ]:
print(cube_dict["top"])

[['y' 'o' 'r']
 ['w' 'w' 'w']
 ['w' 'r' 'r']]


[['o' 'w' 'y']
 ['o' 'g' 'y']
 ['w' 'b' 'r']]
[['o' 'g' 'o']
 ['o' 'w' 'y']
 ['w' 'y' 'r']]


In [ ]:
new_cube = cube_dict

rules_up = [["front", "top"], ["top", "back"], ["back", "bottom"], ["bottom", "front"]]

for i in rules_up:

    print(f"from: {new_cube[i[0]]}")
    print(f"To: {cube_dict[i[1]]}")

    new_cube[i[1]] = cube_dict[i[1]].T
    
    cube_vector = cube_dict[i[0]].T

    new_cube[i[1]][0] = cube_vector[0]
    
    new_cube[i[1]] = new_cube[i[1]].T

    print(f"after: {new_cube[i[1]]}")

    



from: [['b' 'y' 'r']
 ['o' 'y' 'w']
 ['w' 'g' 'g']]
To: [['b' 'r' 'r']
 ['o' 'w' 'b']
 ['w' 'g' 'y']]
after: [['b' 'r' 'r']
 ['o' 'w' 'b']
 ['w' 'g' 'y']]
from: [['b' 'r' 'r']
 ['o' 'w' 'b']
 ['w' 'g' 'y']]
To: [['b' 'g' 'y']
 ['o' 'w' 'o']
 ['w' 'o' 'w']]
after: [['b' 'g' 'y']
 ['o' 'w' 'o']
 ['w' 'o' 'w']]
from: [['b' 'g' 'y']
 ['o' 'w' 'o']
 ['w' 'o' 'w']]
To: [['b' 'o' 'w']
 ['o' 'b' 'r']
 ['w' 'g' 'b']]
after: [['b' 'o' 'w']
 ['o' 'b' 'r']
 ['w' 'g' 'b']]
from: [['b' 'o' 'w']
 ['o' 'b' 'r']
 ['w' 'g' 'b']]
To: [['b' 'y' 'r']
 ['o' 'y' 'w']
 ['w' 'g' 'g']]
after: [['b' 'y' 'r']
 ['o' 'y' 'w']
 ['w' 'g' 'g']]


In [ ]:
print(cube_dict)

print(new_cube)

{'front': array([['y', 'g', 'y'],
       ['r', 'o', 'g'],
       ['g', 'o', 'b']], dtype='<U1'), 'back': array([['y', 'g', 'b'],
       ['r', 'r', 'y'],
       ['w', 'o', 'w']], dtype='<U1'), 'top': array([['y', 'r', 'w'],
       ['g', 'o', 'o'],
       ['y', 'w', 'r']], dtype='<U1'), 'right': array([['w', 'o', 'w'],
       ['b', 'r', 'g'],
       ['g', 'r', 'b']], dtype='<U1'), 'left': array([['g', 'o', 'b'],
       ['r', 'o', 'b'],
       ['g', 'w', 'y']], dtype='<U1'), 'bottom': array([['y', 'r', 'g'],
       ['g', 'y', 'o'],
       ['b', 'y', 'y']], dtype='<U1')}
{'front': array([['y', 'g', 'y'],
       ['r', 'o', 'g'],
       ['g', 'o', 'b']], dtype='<U1'), 'back': array([['y', 'g', 'b'],
       ['r', 'r', 'y'],
       ['w', 'o', 'w']], dtype='<U1'), 'top': array([['y', 'r', 'w'],
       ['g', 'o', 'o'],
       ['y', 'w', 'r']], dtype='<U1'), 'right': array([['w', 'o', 'w'],
       ['b', 'r', 'g'],
       ['g', 'r', 'b']], dtype='<U1'), 'left': array([['g', 'o', 'b'],
       ['r',

In [ ]:
cube_dict["front"] = cube_dict["front"].T
cube_dict["top"] = cube_dict["top"].T

cube_dict["top"][0] = cube_dict["front"][0]

cube_dict["front"] = cube_dict["front"].T
cube_dict["top"] = cube_dict["top"].T

print(cube_dict["front"])
print(cube_dict["top"])

[['b' 'w' 'g']
 ['y' 'w' 'y']
 ['o' 'y' 'b']]
[['b' 'o' 'r']
 ['y' 'w' 'w']
 ['o' 'r' 'r']]


In [14]:

test_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
test_after =  np.rot90(test_vector, k=1, axes=(0, 1))
test_vector, test_after

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[3, 6, 9],
        [2, 5, 8],
        [1, 4, 7]]))

In [ ]:


test_dict = {"front": np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3), "back": np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]).reshape(3, 3)}

new_dict = {}

new = test_dict["back"].T
new[0] = test_dict["front"].T[0]

#new_dict["back"] = new.T

new = test_dict["front"].T
new[0] = test_dict["back"].T[0]

new_dict["front"] = new.T

test_dict

{'front': array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 'back': array([[ 1, 20, 30],
        [ 4, 50, 60],
        [ 7, 80, 90]])}

In [ ]:
a = test_dict["front"].T
a[0]

array([1, 4, 7])

In [ ]:
test_dict["front"].T

array([[100,   4,   7],
       [ 99,   5,   8],
       [  3,   6,   9]])

In [ ]:
test_dict

{'front': array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 'back': array([[ 1, 20, 30],
        [ 4, 50, 60],
        [ 7, 80, 90]])}

In [ ]:
test_dict = {"front": np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3), "back": np.array([10, 20, 30, 40, 50, 60, 70, 80, 90]).reshape(3, 3)}

In [ ]:
test_dict

{'front': array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 'back': array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])}

In [ ]:
a = test_dict["front"].T[0]
b = test_dict["back"].T[1]
print(b)
#new = np.append(a, b).reshape(3, 3).T

#new

80


In [ ]:
test_dict

{'front': array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 'back': array([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])}

In [ ]:
n = range(0, len(test_dict["front"][0]))

n

range(0, 3)

In [ ]:
m = list(n)
m.remove(1)
m

[0, 2]

In [ ]:
d = {1: [1, 2, 3], 3: [1, 2, 3], 2: [1, 2, 3]}



In [ ]:
s = np.array(d[1])
s

array('hej', dtype='<U3')

In [ ]:
s = np.array([d[z] for z in range(1, len(d) + 1)]).reshape(3, 3).T
s

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])